# trapi_agent/state_types.py

"""
Defines the mutable state carried through the LangGraph NL→TRAPI pipeline.

Each node in the graph reads and/or writes fields on TRAPIState.
Fields are all optional (total=False) and are added as processing progresses.
"""

from typing import TypedDict, List, Dict, Any


class TRAPIState(TypedDict, total=False):
    # ────── Immutable input ────────────────────────────────────────────
    query: str
    """The original free-text question."""

    # ────── NER & parsing outputs ──────────────────────────────────────
    ner_spans: List[Dict[str, str]]
    """Raw SpaCy spans: [{'text': ..., 'label': ...}, ...]."""

    entities: List[str]
    """Extracted entity surface strings from the query."""

    generic_types: List[str]
    """Mapped generic Biolink types for each extracted entity."""

    candidate_preds: List[str]
    """Top-k predicate keys from schema for prompting the LLM."""

    predicate: str
    """Free-text predicate string chosen or generated by the LLM."""

    # ────── Resolution outputs ─────────────────────────────────────────
    nodes: Dict[str, Dict[str, Any]]
    """
    Query-graph nodes keyed by node ID (e.g., 'n0'):
      { 'id'?: CURIE, 'name'?: str, 'category': [BiolinkClass], … }
    """

    edges: Dict[str, Dict[str, Any]]
    """
    Query-graph edges keyed by edge ID (e.g., 'e0'):
      { 'subject': node_id, 'object': node_id, 'predicates': [CURIEs], … }
    """

    retrieved_examples: List[Dict[str, Any]]
    """Few-shot examples fetched from Chroma to guide construction."""

    # ────── Validation & repair ────────────────────────────────────────
    errors: List[str]
    """List of validation error messages, if any."""

    valid: bool
    """True if the current output_json passes validation."""

    fix_attempts: int
    """Number of times we have invoked the FixTRAPI node."""

    # ────── Final payload ──────────────────────────────────────────────
    output_json: Dict[str, Any]
    """
    Final TRAPI-compliant JSON to return:
      { 'message': { 'query_graph': { 'nodes': …, 'edges': … } } }
    """
