"""
Defines the mutable state carried through the LangGraph NL→TRAPI pipeline.

Each node in the graph reads and/or writes fields on TRAPIState.
Fields are all optional (total=False) and are added as processing progresses.
"""

from typing import TypedDict, List, Dict, Any, Optional


class TRAPIState(TypedDict, total=False):
    # ────── Immutable input ────────────────────────────────────────────
    query: str
    """The original free-text question."""

    # ────── Routing (must persist across nodes) ────────────────────────
    route: Optional[str]
    """
    The selected pipeline route, e.g., 'onehop', 'pathfinder', 'treats', 'chem_gene'.
    Set by Router or via CLI; consumed by SetRouteFlags/Construct/Validate.
    """
    skip_schema: bool
    """
    If True, ResolveSchema should no-op (e.g., for 'pathfinder').
    Must be preserved across nodes so the spine can branch correctly.
    """

    # ────── NER & parsing outputs ──────────────────────────────────────
    ner_spans: List[Dict[str, str]]
    """Raw SpaCy spans: [{'text': ..., 'label': ...}, ...]."""

    entities: List[str]
    """Extracted entity surface strings from the query."""

    generic_types: List[str]
    """Mapped generic Biolink types inferred from the query (e.g., Protein, Disease)."""

    candidate_preds: List[str]
    """Top-k predicate keys from schema for prompting the LLM."""

    predicate: str
    """Free-text predicate string chosen or generated by the LLM (normalized later)."""

    query_minus_unpinned: str
    """Query with unpinned category text stripped (one-hop helper)."""

    query_minus_entities: str
    """Query with pinned + unpinned text stripped (one-hop helper)."""

    # ────── Resolution outputs ─────────────────────────────────────────
    nodes: Dict[str, Dict[str, Any]]
    """
    Query-graph nodes keyed by node ID (e.g., 'n0'):
      { 'id'?: CURIE, 'name'?: str, 'category': [BiolinkClass], … }
    """

    onehop_parse: Dict[str, Any]
    """Debug payload for one-hop parsing/grounding."""

    edges: Dict[str, Dict[str, Any]]
    """
    (OneHop-style) query-graph edges keyed by edge ID (e.g., 'e0'):
      { 'subject': node_id, 'object': node_id, 'predicates': [CURIEs], … }
    """

    # ────── Pathfinder helpers ─────────────────────────────────────────
    path_nodes: List[str]
    """
    For 'pathfinder' route: the ordered node ids (e.g., ['n0','n1']) used to build/validate paths.p0.
    """

    retrieved_examples: List[Dict[str, Any]]
    """Few-shot examples fetched from Chroma to guide construction (optional)."""

    # ────── Validation & repair ────────────────────────────────────────
    errors: List[str]
    """List of validation error messages, if any."""

    valid: bool
    """True if the current output_json passes validation."""

    fix_attempts: int
    """Number of times we have invoked the FixTRAPI node."""

    # ────── Final payload ──────────────────────────────────────────────
    output_json: Dict[str, Any]
    """
    Final TRAPI-compliant JSON to return:
      { 'message': { 'query_graph': {
            'nodes': {...},
            # OneHop-style:
            'edges': {...},
            # OR Pathfinder-style:
            'paths': {'p0': {'subject': 'n0', 'object': 'n1', 'predicates': ['biolink:related_to']}}
      }}}
    """
